# Generated by Django 3.1.7 on 2021-07-26 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('spouse_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('', 'Gender'), ('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('is_married', models.CharField(choices=[('', 'Is Married'), ('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('dob', models.DateField()),
                ('place_of_birth', models.CharField(max_length=25)),
                ('correspondence_address', models.TextField(max_length=100)),
                ('is_perm_same', models.BooleanField()),
                ('permanent_address', models.TextField(max_length=100)),
                ('pan', models.CharField(max_length=10)),
                ('aadhar', models.CharField(max_length=12)),
                ('education', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Policies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(max_length=15)),
                ('term_plan', models.CharField(max_length=8)),
                ('sum_assured', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
            ],
        ),
    ]
