# Generated by Django 3.1.7 on 2021-07-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
