# Generated by Django 3.1.7 on 2021-07-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210730_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='spouse_name',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
