# Generated by Django 3.1.7 on 2021-08-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210730_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='aadhar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pan',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
