# Generated by Django 3.1.7 on 2021-08-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210803_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='aadhar',
            field=models.CharField(error_messages={'unique': 'Customer with this aadhar already exists'}, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pan',
            field=models.CharField(error_messages={'unique': 'Customer with this pan already exists'}, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='policy_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
