# Generated by Django 3.1.7 on 2021-08-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210806_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='username',
            field=models.CharField(default='pravint198', max_length=150),
            preserve_default=False,
        ),
    ]
