# Generated by Django 3.1.7 on 2021-08-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customers_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='last_name',
            field=models.CharField(default='Invalid', max_length=50),
            preserve_default=False,
        ),
    ]
